### ISSUE TITLE
https://games.hlorenzi.com/ gives 502 Bad Gateway

### ISSUE THREAD

**Issue by bjorn3** [hlorenzi/hlorenzi.github.io#1]
This repo is the best place I could think of to report this.

**Comment by hlorenzi** [comment]
Ah, thank you! Haha.
I've updated Node.js on my server, but I still have to update some apps to use the newer module syntax, so unfortunately they're offline for now... Feel free to also contact me via Discord or Twitter about anything, if you'd like!

**Comment by bjorn3** [comment]
I understand. I was just curious what kind of things your website contained.
